version: '3.8'
services:
  reverse-proxy:
    build: 
      context: reverse_proxy
      dockerfile: Dockerfile
    ports:
      - ${SERVER_PORT}:80
    restart: unless-stopped
  api:
    build: 
      context: .
      dockerfile: Dockerfile
    environment:
      - HOST=${HOST}
      - PORT=${PORT}
    depends_on:
      - reverse-proxy
    restart: unless-stopped
  