version: '3.8'
services:
  reverse-proxy:
    build: 
      context: reverse_proxy
      dockerfile: Dockerfile
    ports:
      - ${SERVER_PORT}:80
  api:
    build: 
      context: .
      dockerfile: Dockerfile
    environment:
      - HOST=${HOST}
      - PORT=${PORT}
  